#!/bin/bash

rm -f temp_results*
rm -f processed_output*

if [ ! -f ./minimax_game ]; then
	make minimax_game
fi

i="0"
team_1_wins="0"
team_2_wins="0"
ties="0"

if [ "$1" = "" ]; then
	games=50
else
	games=$1
fi
	


while [ $i -lt $games ]
do
echo "Running game " $i
./minimax_game $2 > temp_results$i

if [ $i -gt "50" ]; then
	file_num="50"
else
	file_num=$i
fi

if ( cat "temp_results$file_num" | grep "Team 1 wins!!" ); then
	team_1_wins=$[$team_1_wins+1]
fi
if ( cat "temp_results$file_num" | grep "Team 2 wins!!" ); then
	team_2_wins=$[$team_2_wins+1]	
fi
if ( cat "temp_results$file_num" | grep "There was a tie!!" ); then
	ties=$[ties+1]
fi

./process $file_num

i=$[ $i + 1 ]
done

echo "Out of " $games " Games"
echo "There were " $team_1_wins " Team 1 wins"
echo "There were " $team_2_wins " Team 2 wins"
echo "There were " $ties " ties"